# try:
#     while True print("hello")
# except Exception as e:
#     print(e)  # in this case with try except not able to handle error

# Error are something >>>>difficlut to recover
# exception (error)  >>>can be handled
